// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using System;
using WebApplication1.Models;

namespace WebApplication1.Migrations
{
    [DbContext(typeof(MedicamentContext))]
    [Migration("20180507072537_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("WebApplication1.Models.Consumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<int>("MedicamentID");

                    b.Property<double>("RealisationCost");

                    b.Property<string>("RealisationDate");

                    b.HasKey("Id");

                    b.HasIndex("MedicamentID");

                    b.ToTable("Consumptions");
                });

            modelBuilder.Entity("WebApplication1.Models.Medicament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Manufacturer");

                    b.Property<string>("MedicamentName");

                    b.Property<string>("Storage");

                    b.HasKey("Id");

                    b.ToTable("Medicaments");
                });

            modelBuilder.Entity("WebApplication1.Models.Reception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<int>("MedicamentID");

                    b.Property<double>("OrderCost");

                    b.Property<string>("ReceiptDate");

                    b.HasKey("Id");

                    b.HasIndex("MedicamentID");

                    b.ToTable("Receptions");
                });

            modelBuilder.Entity("WebApplication1.Models.Consumption", b =>
                {
                    b.HasOne("WebApplication1.Models.Medicament", "Medicament")
                        .WithMany("Consumptions")
                        .HasForeignKey("MedicamentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("WebApplication1.Models.Reception", b =>
                {
                    b.HasOne("WebApplication1.Models.Medicament", "Medicine")
                        .WithMany("Receptions")
                        .HasForeignKey("MedicamentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
