// <auto-generated />
using ChemistShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace ChemistShop.Migrations
{
    [DbContext(typeof(MedicamentsContext))]
    partial class MedicamentsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("ChemistShop.Models.Consumption", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<int>("MedicamentID");

                    b.Property<int>("RealisationCost");

                    b.Property<DateTime>("RealisationDate");

                    b.HasKey("id");

                    b.HasIndex("MedicamentID");

                    b.ToTable("Consumptions");
                });

            modelBuilder.Entity("ChemistShop.Models.Medicament", b =>
                {
                    b.Property<int>("MedicamentID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Manufacturer");

                    b.Property<string>("MedicamentName");

                    b.Property<int>("Storage");

                    b.HasKey("MedicamentID");

                    b.ToTable("Medicaments");
                });

            modelBuilder.Entity("ChemistShop.Models.Reception", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Count");

                    b.Property<int>("MedicamentID");

                    b.Property<int>("OrderCost");

                    b.Property<string>("Provider");

                    b.Property<DateTime>("ReceiptDate");

                    b.HasKey("id");

                    b.HasIndex("MedicamentID");

                    b.ToTable("Receptions");
                });

            modelBuilder.Entity("ChemistShop.Models.Consumption", b =>
                {
                    b.HasOne("ChemistShop.Models.Medicament", "Medicine")
                        .WithMany("Consumptions")
                        .HasForeignKey("MedicamentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("ChemistShop.Models.Reception", b =>
                {
                    b.HasOne("ChemistShop.Models.Medicament", "Medicine")
                        .WithMany("Receptions")
                        .HasForeignKey("MedicamentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
